import type { Vessel } from "@/lib/content-types";

export const fleetIntro = {
  eyebrow: "Nuestra Flota",
  heading: "Dos catamaranes, dos capitanes",
  body: "Cada charter de Surfnsail se realiza en uno de nuestros dos catamaranes bien equipados: Aventura, capitaneado por Marius, y Exta Sea, capitaneado por Jeremy. Ambos ofrecen el mismo estándar de comodidad, equipo y hospitalidad; elige el que se ajuste a tus fechas, o pregúntanos cuál se adapta mejor a tu viaje.",
};

export const fleet: Vessel[] = [
  {
    slug: "aventura",
    name: "Aventura",
    tagline: "Nuestro catamarán original — amplio, cómodo y listo para todo.",
    makeModel: "Catamarán Robertson & Caine Leopard 40, año 2005",
    captainName: "Marius",
    heroImage: "/aventura/salon.jpg",
    gallery: [
      { src: "/aventura/interior.jpg", width: 1536, height: 1152, alt: "Bar de la cabina de Aventura, decorado con flores frescas, fondeado junto a un manglar" },
      { src: "/aventura/interior2.jpeg", width: 1599, height: 1066, alt: "Asientos de la cabina de popa y timón de Aventura" },
      { src: "/aventura/interior3.jpeg", width: 2048, height: 1152, alt: "Cocina de Aventura con vista a la cubierta de popa al atardecer" },
      { src: "/aventura/cabin.jpeg", width: 1024, height: 1536, alt: "Una de las cuatro cabinas de Aventura" },
      { src: "/aventura/cabin2.jpg", width: 1152, height: 1536, alt: "Litera de una cabina de Aventura con luz de lectura" },
      { src: "/aventura/toilet.jpg", width: 1536, height: 1152, alt: "Uno de los dos baños de Aventura" },
    ],
    specs: [
      { label: "Cabinas", value: "4 cabinas, 6 literas" },
      { label: "Capacidad", value: "8 adultos + 2 niños" },
      { label: "Baños", value: "2" },
      { label: "Energía", value: "Tomas de 220V / 110V" },
      { label: "Motores", value: "2× 40 hp Volvo Penta" },
      { label: "Capitán", value: "Marius" },
    ],
    amenities: [
      "Aire acondicionado",
      "Generador",
      "Desalinizador de agua",
      "Ventilador y luces de lectura en cada cabina",
      "Cocina completa",
      "Máquina Nespresso",
      "Parrilla (BBQ)",
      "Bote auxiliar Caribe con motor de 25 hp",
      "Equipo de pesca, snorkel y pesca submarina",
      "Tabla de paddle (SUP)",
      "Colchón flotante, bar flotante y flotadores",
      "WiFi (dentro de cobertura)",
      "Teléfono satelital (emergencias)",
    ],
    description: [
      "Un Robertson & Caine Leopard 40 del año 2005, Aventura es el bote con el que empezó todo: cuatro cabinas repartidas en dos cascos, una cocina completa y una cubierta pensada para relajarse entre isla e isla. Marius la ha capitaneado durante años y conoce cada arrecife y fondeadero de Bocas del Toro.",
    ],
  },
  {
    slug: "exta-sea",
    name: "Exta Sea",
    tagline: "Un crucero oceánico probado con cuatro cabinas privadas — amplio, cómodo, ideal para recibir invitados.",
    makeModel: "Catamarán Leopard 47, año 1998",
    captainName: "Jeremy",
    heroImage: "/catamaran2.jpeg",
    gallery: [
      { src: "/catamaran.jpeg", width: 4032, height: 3024, alt: "Exta Sea fondeado en el archipiélago de Bocas del Toro" },
      { src: "/deck.jpeg", width: 4032, height: 3024, alt: "Cubierta de proa y red de trampolín de Exta Sea" },
      { src: "/deck2.jpeg", width: 4032, height: 3024, alt: "Cubierta de Exta Sea, velas recogidas" },
      { src: "/outdoorsalonbackboat.jpeg", width: 4032, height: 3024, alt: "Salón de popa de Exta Sea" },
      { src: "/outdoorsalonbackboat2.jpeg", width: 4032, height: 3024, alt: "Asientos alrededor de la mesa de cabina de Exta Sea" },
      { src: "/livingroomsailboat.jpeg", width: 4032, height: 3024, alt: "Asientos del salón de Exta Sea" },
      { src: "/livingroomsailboat2.jpeg", width: 4032, height: 3024, alt: "Salón de Exta Sea, vista hacia la cocina" },
      { src: "/inside.jpeg", width: 3024, height: 4032, alt: "Interior bajo cubierta de Exta Sea" },
      { src: "/bathroom.jpeg", width: 3024, height: 4032, alt: "Uno de los baños de Exta Sea" },
      { src: "/fridgewashingmachine.jpeg", width: 3024, height: 4032, alt: "Nevera y lavadora de la cocina de Exta Sea" },
      { src: "/skipper2.jpeg", width: 2160, height: 3840, alt: "El capitán Jeremy al timón de Exta Sea" },
      { src: "/skipper3.jpeg", width: 2316, height: 3088, alt: "El capitán Jeremy a bordo de Exta Sea" },
      { src: "/fishing.jpeg", width: 1536, height: 2048, alt: "Equipo de pesca preparado a bordo de Exta Sea" },
      { src: "/fishing2.jpeg", width: 3024, height: 4032, alt: "La captura de un huésped a bordo de Exta Sea" },
    ],
    specs: [
      { label: "Cabinas", value: "4 cabinas (3 para huéspedes + 1 tripulación)" },
      { label: "Baños", value: "4, todos en suite" },
      { label: "Bote auxiliar", value: "RIB de 12 pies con motor de 20 hp" },
      { label: "Capitán", value: "Jeremy" },
    ],
    amenities: [
      "Equipo de snorkel",
      "Cine al aire libre (con máquina de palomitas)",
      "2 tablas de paddle (SUP)",
      "Colchón flotante para hasta 6 huéspedes",
      "Hamaca",
      "2 esterillas de yoga",
      "Lavadora/secadora",
      "Sombrilla grande de playa",
      "Toallas, paños, champú y jabón corporal incluidos",
      "Dron 4K y GoPro para capturar el viaje",
    ],
    description: [
      "Exta Sea es un catamarán Leopard 47 de 1998 — un crucero oceánico probado, reconocido por su durabilidad, comodidad y diseño práctico, capitaneado por Jeremy. Cuenta con cuatro cabinas y cuatro baños en suite (tres cabinas para huéspedes más una para la tripulación), así que todos tienen su propia privacidad. Hay mucho espacio en cubierta, una cocina y salón amplios, y una bañera espaciosa ideal tanto para comer como para socializar — con parrilla y plancha incluidas.",
      "Relájate en los trampolines de proa o en los dos asientos de proa — el mejor lugar a bordo para ver pasar un grupo de delfines, o para el clásico gesto de \"rey del mundo\".",
      "Nuestros huéspedes suelen decir que Exta Sea se siente como un hogar lejos de casa, con todo lo necesario para navegar las islas de Bocas del Toro con comodidad y estilo.",
    ],
  },
];
