import type { Vessel } from "@/lib/content-types";

export const fleetIntro = {
  eyebrow: "Our Fleet",
  heading: "Two catamarans, two captains",
  body: "Every Surfnsail charter is built around one of two well-equipped catamarans — Aventura, captained by Marius, and Exta Sea, captained by Jeremy. Both carry the same standard of comfort, gear and hospitality; pick the one that fits your dates, or ask us which suits your trip best.",
};

export const fleet: Vessel[] = [
  {
    slug: "aventura",
    name: "Aventura",
    tagline: "Our original catamaran — spacious, comfortable, ready for anything.",
    makeModel: "2005 Robertson & Caine Leopard 40 catamaran",
    captainName: "Maga",
    heroImage: "/aventura/salon.jpg",
    gallery: [
      { src: "/aventura/interior.jpg", width: 1536, height: 1152, alt: "Aventura's cockpit bar, styled with fresh flowers, anchored off a mangrove shoreline" },
      { src: "/aventura/interior2.jpeg", width: 1599, height: 1066, alt: "Aventura's aft cockpit seating and helm" },
      { src: "/aventura/interior3.jpeg", width: 2048, height: 1152, alt: "Aventura's galley opening onto the aft deck at dusk" },
      { src: "/aventura/cabin.jpeg", width: 1024, height: 1536, alt: "One of Aventura's four guest cabins" },
      { src: "/aventura/cabin2.jpg", width: 1152, height: 1536, alt: "Aventura cabin bunk with reading light" },
      { src: "/aventura/toilet.jpg", width: 1536, height: 1152, alt: "One of Aventura's two heads" },
    ],
    specs: [
      { label: "Cabins", value: "4 staterooms (3 guest + 1 crew)" },
      { label: "Capacity", value: "6 adults + 2 kids" },
      { label: "Heads", value: "2" },
      { label: "Power", value: "220V / 110V outlets" },
      { label: "Engines", value: "2× 40 hp Volvo Penta" },
      { label: "Captain", value: "Maga (Marius as backup)" },
    ],
    amenities: [
      "Air conditioning",
      "Generator",
      "Starlink internet",
      "Full galley",
      "BBQ",
      "Caribe dinghy w/ 15 hp outboard",
      "Fishing, snorkeling & spearfishing gear",
      "Stand-up paddleboard",
      "Floating mat & pool noodles",
      "Satellite phone (emergencies)",
    ],
    description: [
      "A 2005 Robertson & Caine Leopard 40, Aventura is the boat that started it all — four staterooms across two hulls, a full galley, and a deck built for lounging between islands. Captain Maga has skippered her for years and knows every reef and anchorage in Bocas del Toro, with Marius stepping in whenever a backup captain is needed.",
    ],
  },
  {
    slug: "exta-sea",
    name: "Exta Sea",
    tagline: "A proven bluewater cruiser with four private staterooms — spacious, comfortable, built for entertaining.",
    makeModel: "1998 Leopard 47 catamaran",
    captainName: "Jeremy",
    heroImage: "/catamaran2.jpeg",
    gallery: [
      { src: "/catamaran.jpeg", width: 4032, height: 3024, alt: "Exta Sea at anchor in the Bocas del Toro archipelago" },
      { src: "/deck.jpeg", width: 4032, height: 3024, alt: "Exta Sea's foredeck and trampoline netting" },
      { src: "/deck2.jpeg", width: 4032, height: 3024, alt: "Exta Sea's deck, sails furled" },
      { src: "/outdoorsalonbackboat.jpeg", width: 4032, height: 3024, alt: "Exta Sea's aft cockpit lounge" },
      { src: "/outdoorsalonbackboat2.jpeg", width: 4032, height: 3024, alt: "Seating around the cockpit table aboard Exta Sea" },
      { src: "/livingroomsailboat.jpeg", width: 4032, height: 3024, alt: "Exta Sea's saloon seating" },
      { src: "/chill.jpeg", width: 4032, height: 3024, alt: "Exta Sea's saloon, view toward the galley" },
      { src: "/cabin.jpeg", width: 1200, height: 900, alt: "One of Exta Sea's guest cabins, with a beach-themed triptych above the berth" },
      { src: "/cabin2.jpeg", width: 1200, height: 1600, alt: "Exta Sea guest cabin berth, view toward the ensuite steps" },
      { src: "/inside.jpeg", width: 3024, height: 4032, alt: "Below deck aboard Exta Sea" },
      { src: "/bathroom.jpeg", width: 3024, height: 4032, alt: "One of Exta Sea's heads" },
      { src: "/fridgewashingmachine.jpeg", width: 3024, height: 4032, alt: "Exta Sea's galley fridge and washing machine" },
      { src: "/skipper2.jpeg", width: 2160, height: 3840, alt: "Captain Jeremy at the helm of Exta Sea" },
      { src: "/skipper3.jpeg", width: 2316, height: 3088, alt: "Captain Jeremy aboard Exta Sea" },
      { src: "/fishing.jpeg", width: 1536, height: 2048, alt: "Fishing gear rigged aboard Exta Sea" },
      { src: "/fishing2.jpeg", width: 3024, height: 4032, alt: "A guest's catch aboard Exta Sea" },
    ],
    specs: [
      { label: "Cabins", value: "4 staterooms (3 guest + 1 crew)" },
      { label: "Heads", value: "4, each en-suite" },
      { label: "Dinghy", value: "12 ft RIB w/ 20 hp outboard" },
      { label: "Captain", value: "Jeremy" },
    ],
    amenities: [
      "Snorkeling gear",
      "Outdoor cinema (with popcorn maker)",
      "2 stand-up paddleboards",
      "Floating mattress for up to 6 guests",
      "Hammock",
      "2 yoga mats",
      "Washer/dryer",
      "Large beach umbrella",
      "Towels, washcloths, shampoo & body wash included",
      "4K drone & GoPro for capturing the trip",
    ],
    description: [
      "Exta Sea is a 1998 Leopard 47 catamaran — a proven bluewater cruiser renowned for its durability, comfort and practical design, captained by Jeremy. She sleeps in four staterooms with four en-suite heads (three guest cabins plus one crew cabin), so everyone has their own privacy. Expect plenty of deck space, a large galley and salon, and a spacious cockpit built for both dining and entertaining — BBQ and griddle included.",
      "Relax on the bow trampolines or the two bow seats — the best spot onboard for a passing pod of dolphins, or a classic “king of the world” moment.",
      "Guests consistently say Exta Sea feels like a home away from home, with everything you need to cruise the islands of Bocas del Toro in comfort and style.",
    ],
  },
];
